### PR TITLE
fix(shader): add GLSL 150/140/130 targets for desktop GPU compat

### PR DESCRIPTION
**Pull request by edward-abrosimov**
## Summary

Extends `qt_add_shaders` GLSL targets so QmlMaterial shaders compile on desktop GPUs/drivers that only expose older OpenGL shader profiles.

- **Was:** `"300es,330"`
- **Now:** `"150,140,130,330,300es"`

## Problem

Shaders power core M3 visuals: rounded rectangles, shadows, blur masks, ripples (`assets/shader/*.frag`, `*.vert`). On some Linux desktop setups with legacy GL profiles, only GLSL 1.x targets are available; limiting targets to 330/300es can fail shader compilation at build or runtime.

## Changes

| File | Change |
|------|--------|
| `CMakeLists.txt` | Broader `GLSL` list in `qt_add_shaders` for target `qml_material` |

Affected shader pipeline (unchanged sources, more compile targets):

- `shadow.vert` / `shadow.frag`
- `rectangle.vert` / `rectangle.frag`
- `sdf_rectangle.frag`, `round_clip.frag`
- `blur_mask.vert` / `blur_mask.frag`
- `ripple.frag`, `rect_glow.frag`

## Review focus

- Build time / `.qsb` artifact size increase from extra GLSL variants
- Qt picks the best available variant at runtime — order in the list matters for fallback
- WebAssembly / ES-only builds — `300es` retained

## Test plan

- [ ] Clean configure + `cmake --build . --target qml_material` — green
- [ ] `qm_example` — cards, elevation, rounded images, ripples render correctly
- [ ] On a machine with older GL (if available) — no shader compile warnings in log

## Known limitations / follow-up

Non-blocking for merge:

1. No CI matrix entry for legacy GL drivers yet
2. Could gate extra targets behind a CMake option if build-time cost is a concern

### CODE REVIEW

**Comment by hypengw** [comment]
Why `150`,`140`,`130`?
I think only one is needed.

**Comment by edward-abrosimov** [comment]
Adding all three targets (130, 140, 150) is necessary because:

- They correspond to different OpenGL versions (3.0, 3.1, 3.2+) – see the [OpenGL Shading Language version table](https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#Versions).
- Without 130 and 140, shaders will not compile on systems with OpenGL 3.0/3.1.
- The order is important: Qt chooses the first matching target at runtime, so the list should be as broad as possible for correct fallback.

If you leave only 150, then:
- Users with OpenGL 3.0/3.1 will get a shader compilation error.
- On some drivers, 150 may be missing, while 130/140 are present.

Therefore, I leave all three – this is the standard set for desktop compatibility. In fact, Qt's own `--qt6` flag expands to `--glsl "100 es,120,150"` for desktop targets, which is "commonly used with shaders for Qt Quick materials and effects" ([Qt Shader Tools – `qsb` docs](https://doc.qt.io/qt-6/qtshadertools-qsb.html#qt6)). Adding 130 and 140 alongside 150 follows the same principle of providing broad GLSL version coverage for maximum driver compatibility.

**Sources:**
- [Qt Shader Tools – `qsb` manual: `--qt6` option](https://doc.qt.io/qt-6/qtshadertools-qsb.html#qt6) – "This set is commonly used with shaders for Qt Quick materials and effects"
- [OpenGL Wiki – Core Language (GLSL) versions](https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#Versions) – GLSL 130 ↔ OpenGL 3.0, 140 ↔ 3.1, 150 ↔ 3.2

**Comment by edward-abrosimov** [comment]
So, @hypengw, what do you think of these improvements? I work on desktop applications for Ubuntu 20.4, so these improvements were important in my case.
